# Site settings
title: Jekyll Example Site
description: "Example site using Jekyll and Github Pages"
baseurl: "/jekyll-example.github.io/" # the subpath of your site, e.g. /blog/
url: "http://http://justinrcook.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


include:
  - .nojekyll

exclude:
  - bower_components
  - node_modules
  - bower.json
  - package.json
  - Gruntfile.coffee
  - Rakefile
